import { api, randomActionId, setupAuth } from "./app-client.js";
import { renderPackPreview } from "./pack-preview.js";

const panel=document.querySelector("[data-moderation]");const queue=document.querySelector("[data-queue]");const status=document.querySelector("[data-moderation-status]");const workspace=document.querySelector("[data-review-workspace]");let active=null;
setupAuth(async()=>{panel.hidden=false;await loadQueue();});
document.querySelector("[data-refresh]").addEventListener("click",loadQueue);document.querySelector("[data-status-filter]").addEventListener("change",loadQueue);document.querySelector("[data-close]").addEventListener("click",()=>workspace.hidden=true);
document.querySelector("[data-add-feedback]").addEventListener("click",addFeedback);document.querySelector("[data-request-changes]").addEventListener("click",()=>transition("changes_requested"));document.querySelector("[data-language-approve]").addEventListener("click",()=>transition("language_approved"));document.querySelector("[data-reject]").addEventListener("click",()=>transition("rejected"));
document.querySelector("[data-admin-approve]").addEventListener("click",()=>transition("approved"));document.querySelector("[data-publish]").addEventListener("click",()=>transition("published"));document.querySelector("[data-archive]").addEventListener("click",()=>transition("archived"));

async function loadQueue(){setStatus("Loading queue…");try{const filter=document.querySelector("[data-status-filter]").value;const data=await api(`/api/moderation?action=queue&status=${encodeURIComponent(filter)}`);queue.replaceChildren();for(const item of data.submissions){const tr=document.createElement("tr");const warning=item.possible_duplicate?`Possible duplicate · ${Math.round(Number(item.duplicate_similarity||0)*100)}%`:(item.content_hash?`Hash ${item.content_hash.slice(0,10)}…`:"Not calculated");tr.append(cell(item.title),cell(item.creation_method==="upload"?"Uploaded":"AI generated"),cell(`${item.target_language} → ${item.base_language}`),cell(warning),cell(item.state),cell(new Date(item.created_at).toLocaleString()));const action=document.createElement("td");const assigned=item.moderation_assignments?.find((a)=>a.state==="active");const button=document.createElement("button");button.className="button secondary";button.textContent=assigned?"Open review":"Claim";button.addEventListener("click",async()=>{try{if(!assigned)await api("/api/moderation",{method:"POST",body:{action:"claim",submissionId:item.id,version:item.current_version}});await openWorkspace(item.id);}catch(error){setStatus(error.message);}});action.append(button);tr.append(action);queue.append(tr);}if(!data.submissions.length){const tr=document.createElement("tr");const td=cell("No submissions match this queue.");td.colSpan=7;tr.append(td);queue.append(tr);}setStatus(`${data.submissions.length} submission(s).`,true);}catch(error){setStatus(error.message);}}
async function openWorkspace(id){try{const data=await api(`/api/moderation?action=workspace&id=${encodeURIComponent(id)}`);active=data;const version=data.versions.find((v)=>v.version===data.submission.current_version);document.querySelector("[data-review-title]").textContent=data.submission.title;document.querySelector("[data-review-meta]").textContent=`${data.submission.target_language} → ${data.submission.base_language} · ${version.creation_method==="upload"?"Uploaded":"AI generated"} · version ${version.version} · ${data.submission.state}${version.possible_duplicate?` · possible duplicate (${Math.round(Number(version.duplicate_similarity||0)*100)}%)`:""}`;document.querySelector("[data-language-approve]").hidden=data.submission.state!=="submitted";document.querySelector("[data-admin-approve]").hidden=data.submission.state!=="language_approved";document.querySelector("[data-publish]").hidden=data.submission.state!=="approved";document.querySelector("[data-archive]").hidden=data.submission.state!=="published";renderPackPreview(version.canonical_json,document.querySelector("[data-review-preview]"),{label:"Reviewed pack"});const target=document.querySelector("[data-review-sentences]");target.replaceChildren();for(const reason of version.duplicate_reasons||[])target.append(node("p",`Near-duplicate warning: ${reason}`,"workspace-notice"));for(const feedback of data.feedback)target.append(node("p",`Feedback v${feedback.submission_version} · ${feedback.category}: ${feedback.body}`,"workspace-notice"));workspace.hidden=false;workspace.scrollIntoView({behavior:"smooth"});}catch(error){setStatus(error.message);}}
async function addFeedback(){if(!active)return;const body=document.querySelector("[data-feedback]").value.trim();if(!body){setStatus("Write feedback first.");return;}try{await api("/api/moderation",{method:"POST",body:{action:"feedback",submissionId:active.submission.id,version:active.submission.current_version,category:document.querySelector("[data-feedback-category]").value,body}});document.querySelector("[data-feedback]").value="";await openWorkspace(active.submission.id);setStatus("Feedback saved.",true);}catch(error){setStatus(error.message);}}
async function transition(nextState){if(!active)return;const needsReason=["changes_requested","rejected","archived"].includes(nextState);const reason=needsReason?window.prompt(`Reason for ${nextState.replace("_"," ")}:`,document.querySelector("[data-feedback]").value):"";if(needsReason&&!reason)return;if(["published","archived","rejected"].includes(nextState)&&!window.confirm(`Confirm ${nextState.replace("_"," ")} for this immutable version?`))return;try{await api("/api/moderation",{method:"POST",idempotencyKey:randomActionId("transition"),body:{action:"transition",submissionId:active.submission.id,version:active.submission.current_version,rowVersion:active.submission.row_version,nextState,reason}});workspace.hidden=true;await loadQueue();setStatus(`Submission moved to ${nextState.replace("_"," ")}.`,true);}catch(error){setStatus(error.message);}}
function cell(value){return node("td",value);}function node(tag,value,className){const el=document.createElement(tag);el.textContent=String(value??"");if(className)el.className=className;return el;}function format(items){return items?.map((x)=>x.surface||x.pattern).join(", ")||"none";}function setStatus(message,success=false){status.textContent=message;status.className=success?"workspace-success":"workspace-error";}
