"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "@/lib/website-api";

type Annotation = Record<string, unknown>;
type Sentence = { text: string; translation: string; words?: Annotation[]; grammar?: Annotation[]; chunks?: Annotation[] };
type Lesson = { title: string; description?: string; source?: string; level?: string; tags?: string[]; sentences: Sentence[] };
type Pack = { id: string; title: string; description?: string; author?: Record<string, string>; version: string; language: string; baseLanguage: string; level?: string; tags?: string[]; lessons: Lesson[] };
type Version = { version: number; source_draft_revision: number; canonical_json: Pack; submitted_at: string; contributor_note?: string | null; validation: { warnings: Array<{ path: string; message: string }>; lessonCount: number; sentenceCount: number } };
type Feedback = { id: string; submission_version: number; target_type: string; target_path: string | null; lesson_index: number | null; sentence_index: number | null; category: string; body: string; visibility: string; resolution_state: string; created_at: string };
type Event = { id: string; event_type: string; previous_state: string | null; next_state: string | null; reason: string | null; submission_version: number | null; created_at: string; actor?: { email: string } };
type Workspace = { submission: { id: string; title: string; state: string; current_version: number; row_version: number; target_language: string; base_language: string; created_at: string; contributor?: { email: string; display_name: string | null } }; versions: Version[]; feedback: Feedback[]; events: Event[] };

export function AdminSubmissionReview({ submissionId }: { submissionId: string }) {
  const [data, setData] = useState<Workspace | null>(null); const [status, setStatus] = useState(""); const [selectedVersion, setSelectedVersion] = useState<number | null>(null); const [lessonIndex, setLessonIndex] = useState(0); const [query, setQuery] = useState(""); const [flagsOnly, setFlagsOnly] = useState(false);
  const load = useCallback(async () => { try { const result = await api<Workspace>(`/api/moderation?action=workspace&id=${submissionId}`); setData(result); setSelectedVersion((current) => current ?? result.submission.current_version); setStatus(""); } catch (error) { setStatus(message(error)); } }, [submissionId]);
  useEffect(() => { void load(); }, [load]);
  const version = useMemo(() => data?.versions.find((item) => item.version === selectedVersion) || data?.versions[0], [data, selectedVersion]);
  const pack = version?.canonical_json; const lesson = pack?.lessons[lessonIndex];
  const feedback = useMemo(() => (data?.feedback || []).filter((item) => item.submission_version === version?.version), [data, version]);
  const sentences = useMemo(() => (lesson?.sentences || []).map((sentence, index) => ({ sentence, index })).filter(({ sentence, index }) => { const matches = !query || `${sentence.text} ${sentence.translation}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()); const flagged = feedback.some((item) => item.lesson_index === lessonIndex && item.sentence_index === index); return matches && (!flagsOnly || flagged); }), [lesson, query, flagsOnly, feedback, lessonIndex]);
  async function flag(targetType: string, targetPath: string, indexes: { lessonIndex?: number; sentenceIndex?: number } = {}) { if (!data || !version) return; const note = window.prompt(`Moderation note for ${targetPath}:`); if (!note) return; const internal = window.confirm("Keep this flag internal? Select Cancel to share it with the contributor."); try { await api("/api/moderation", { method: "POST", body: { action: "feedback", submissionId: data.submission.id, version: version.version, targetType, targetPath, lessonIndex: indexes.lessonIndex, sentenceIndex: indexes.sentenceIndex, category: targetType === "annotation" ? "annotation" : "other", body: note, internal } }); await load(); } catch (error) { setStatus(message(error)); } }
  async function transition(nextState: string, title: string, requiresReason = false) { if (!data) return; const reason = requiresReason ? window.prompt(`Moderation note required to ${title.toLocaleLowerCase()}:`) : window.prompt("Optional moderation note:"); if (requiresReason && !reason) return; if (!window.confirm(`${title} “${data.submission.title}” revision ${data.submission.current_version}?`)) return; try { const result = await api<{ submission: { state: string } }>("/api/moderation", { method: "POST", idempotencyKey: `admin:${nextState}:${crypto.randomUUID()}`, body: { action: "transition", submissionId: data.submission.id, version: data.submission.current_version, rowVersion: data.submission.row_version, nextState, reason } }); setStatus(`Submission is now ${result.submission.state.replaceAll("_", " ")}.`); await load(); } catch (error) { setStatus(message(error)); } }
  if (!data || !version || !pack) return <section className="workspace-card"><Link className="text-link" href="/admin/moderation">← Moderation queue</Link>{status ? <p className="admin-alert">{status}</p> : <p>Loading submission…</p>}</section>;
  const actions = moderationActions(data.submission.state);
  return <div className="stack"><section className="workspace-card admin-panel"><Link className="text-link" href="/admin/moderation">← Moderation queue</Link><div className="workspace-header"><div><span className="eyebrow">Immutable submission revision</span><h1>{pack.title}</h1><p>{data.submission.contributor?.display_name || data.submission.contributor?.email} · {pack.language} → {pack.baseLanguage} · {pack.level || "level not set"}</p></div><span className="pill pill-accent">{data.submission.state.replaceAll("_", " ")}</span></div>
    <div className="metadata-grid"><div><small>Pack version</small><strong>{pack.version}</strong></div><div><small>Submission revision</small><strong>{version.version}</strong></div><div><small>Draft revision</small><strong>{version.source_draft_revision}</strong></div><div><small>Lessons</small><strong>{version.validation.lessonCount}</strong></div><div><small>Sentences</small><strong>{version.validation.sentenceCount}</strong></div><div><small>Submitted</small><strong>{new Date(version.submitted_at).toLocaleString()}</strong></div></div>
    <div className="workspace-actions">{actions.map((action) => <button key={action.label} className={`button ${action.destructive ? "danger" : action.secondary ? "secondary" : ""}`} onClick={() => void transition(action.next, action.label, action.reason)}>{action.label}</button>)}</div>{status && <p className="admin-alert" role="status">{status}</p>}
    <div className="metadata-review"><h2>Pack metadata</h2><p>{pack.description || "No description."}</p><p>Author: {pack.author?.name || "Contributor"} · Tags: {pack.tags?.join(", ") || "none"}</p><p>Contributor note: {version.contributor_note || "None"}</p><button className="button secondary" onClick={() => void flag("metadata", "pack metadata")}>Flag metadata</button></div>
    {version.validation.warnings.length ? <div className="admin-alert"><strong>Automated validation</strong>{version.validation.warnings.map((warning) => <p key={`${warning.path}:${warning.message}`}>{warning.path}: {warning.message}</p>)}</div> : <p className="validation-ok">Automated validation passed for this immutable revision.</p>}
  </section>
  <section className="workspace-card admin-panel"><div className="workspace-header"><div><span className="eyebrow">Content review</span><h2>Lessons and sentences</h2></div><label>Revision<select value={version.version} onChange={(event) => { setSelectedVersion(Number(event.target.value)); setLessonIndex(0); }}>{data.versions.map((item) => <option key={item.version} value={item.version}>Submission v{item.version} · draft r{item.source_draft_revision}</option>)}</select></label></div>
    <div className="admin-filters"><label>Lesson<select value={lessonIndex} onChange={(event) => setLessonIndex(Number(event.target.value))}>{pack.lessons.map((item, index) => <option value={index} key={`${item.title}:${index}`}>{index + 1}. {item.title}</option>)}</select></label><label>Find sentence<input value={query} onChange={(event) => setQuery(event.target.value)} /></label><label className="checkbox"><input type="checkbox" checked={flagsOnly} onChange={(event) => setFlagsOnly(event.target.checked)} /> Flagged only</label></div>
    {lesson && <div className="lesson-review"><div className="workspace-header"><div><h2>{lesson.title}</h2><p>{lesson.description || "No lesson description."} {lesson.source ? `Source: ${lesson.source}` : ""}</p></div><button className="button secondary" onClick={() => void flag("lesson", `lessons[${lessonIndex}]`, { lessonIndex })}>Flag lesson</button></div>{sentences.map(({ sentence, index }) => <article className="sentence-review" id={`sentence-${index}`} key={index}><div className="workspace-header"><div><span className="eyebrow">Sentence {index + 1}</span><h3>{sentence.text}</h3><p>{sentence.translation}</p></div><button className="button secondary" onClick={() => void flag("sentence", `lessons[${lessonIndex}].sentences[${index}]`, { lessonIndex, sentenceIndex: index })}>Flag sentence</button></div>{(["words", "grammar", "chunks"] as const).map((kind) => Boolean(sentence[kind]?.length) && <div className="annotation-list" key={kind}><strong>{kind}</strong>{sentence[kind]?.map((annotation, annotationIndex) => <div key={annotationIndex}><code>{Object.entries(annotation).map(([key, value]) => `${key}: ${Array.isArray(value) ? value.join(", ") : String(value)}`).join(" · ")}</code><button className="text-button" onClick={() => void flag("annotation", `lessons[${lessonIndex}].sentences[${index}].${kind}[${annotationIndex}]`, { lessonIndex, sentenceIndex: index })}>Flag</button></div>)}</div>)}{feedback.filter((item) => item.lesson_index === lessonIndex && item.sentence_index === index).map((item) => <p className="flag-note" key={item.id}>{item.visibility === "internal" ? "Internal" : "Contributor-visible"}: {item.body}</p>)}</article>)}</div>}
  </section>
  <section className="workspace-card admin-panel"><h2>Flags and moderator feedback</h2><div className="card-list">{feedback.map((item) => <article className="flag-note" key={item.id}><strong>{item.target_type} · {item.target_path || "pack"}</strong><p>{item.body}</p><small>{item.visibility} · {item.resolution_state} · {new Date(item.created_at).toLocaleString()}</small></article>)}{!feedback.length && <p>No flags on this revision.</p>}</div></section>
  <section className="workspace-card admin-panel"><h2>Moderation history</h2><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Revision</th><th>Transition</th><th>Reason</th></tr></thead><tbody>{data.events.map((event) => <tr key={event.id}><td>{new Date(event.created_at).toLocaleString()}</td><td>{event.actor?.email || "System"}</td><td>{event.event_type.replaceAll("_", " ")}</td><td>{event.submission_version ? `v${event.submission_version}` : "—"}</td><td>{event.previous_state || "—"} → {event.next_state || "—"}</td><td>{event.reason || "—"}</td></tr>)}</tbody></table></div></section></div>;
}

function moderationActions(state: string) { if (state === "submitted") return [{ label: "Approve", next: "approved" }, { label: "Request changes", next: "changes_requested", reason: true, secondary: true }, { label: "Reject", next: "rejected", reason: true, destructive: true }, { label: "Archive", next: "archived", reason: true, destructive: true }]; if (state === "language_approved") return [{ label: "Approve", next: "approved" }, { label: "Request changes", next: "changes_requested", reason: true, secondary: true }, { label: "Reject", next: "rejected", reason: true, destructive: true }]; if (state === "approved") return [{ label: "Publish", next: "published" }, { label: "Request changes", next: "changes_requested", reason: true, secondary: true }, { label: "Archive", next: "archived", reason: true, destructive: true }]; if (state === "published") return [{ label: "Unpublish", next: "approved", secondary: true }, { label: "Archive", next: "archived", reason: true, destructive: true }]; if (["rejected", "changes_requested"].includes(state)) return [{ label: "Archive", next: "archived", reason: true, destructive: true }]; if (state === "archived") return [{ label: "Restore", next: "restore" }]; return []; }
function message(error: unknown) { return error instanceof Error ? error.message : "The request could not be completed."; }
